package recipe_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class delete_recipe extends javax.swing.JFrame {

    /**
     * Creates new form delete_recipe
     */
    public delete_recipe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        HomeBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(488, 330));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 20)); // NOI18N
        jLabel1.setText("DELETE RECIPE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 30, 171, 26);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("ENTER RECIPE ID:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(69, 90, 123, 17);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(69, 172, 0, 0);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("OR");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(209, 122, 21, 17);

        HomeBtn.setBackground(new java.awt.Color(255, 0, 51));
        HomeBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        HomeBtn.setForeground(new java.awt.Color(255, 255, 255));
        HomeBtn.setText("GO BACK TO HOME");
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(HomeBtn);
        HomeBtn.setBounds(49, 219, 169, 25);

        DeleteBtn.setBackground(new java.awt.Color(0, 0, 204));
        DeleteBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        DeleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        DeleteBtn.setText("DELETE");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteBtn);
        DeleteBtn.setBounds(293, 220, 85, 25);
        getContentPane().add(t1);
        t1.setBounds(262, 87, 153, 30);
        getContentPane().add(t2);
        t2.setBounds(260, 150, 153, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("ENTER RECIPE NAME:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(76, 156, 150, 17);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete-recipe.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, -80, 630, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        int res = JOptionPane.showConfirmDialog(null, "Are you sure?");
        if (res == JOptionPane.YES_OPTION) {
         try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String db = "jdbc:mysql://localhost:3306/recipe_system?zeroDateTimeBehavior=convertToNull";
            Connection con = DriverManager.getConnection(db, "root", "P@ssw0rd");
            Statement stmt = con.createStatement();

                if (!isNullOrEmpty(t1.getText())) {
                    String query = "delete from recipe where RecipeID = " + t1.getText() + ";";
                    stmt.executeUpdate(query);
                    
                    String query2 = "delete from recipeingredients where recipeid="+ t1.getText() +";";
                    stmt.executeUpdate(query2);
                    
                    JOptionPane.showMessageDialog(null, "This Recipe is removed from the system.");
                    t1.setText(" ");
                }

                if (!isNullOrEmpty(t2.getText())) {
                    int RecipeID = 0;
                    
                    String selectQuery = "select recipeid from recipe where name = '" + t2.getText() + "';";
                    ResultSet rs = stmt.executeQuery(selectQuery);
                    
                    while (rs.next()) {
                        RecipeID = rs.getInt("RecipeID");
                    }
                    
                    if(RecipeID > 0) {
                            String query = "delete from recipe where RecipeID = " + RecipeID + ";";
                            stmt.executeUpdate(query);
                            
                            String query2 = "delete from recipeingredients where RecipeID = " +  RecipeID + ";";
                            stmt.executeUpdate(query2);
                        
                            JOptionPane.showMessageDialog(null, "This Recipe is removed from the system.");
                            t2.setText(" ");
                    } else {
                        JOptionPane.showMessageDialog(null, "Recipe not found. Try again.");
                    }

                    rs.close();
                }
                
                stmt.close();
                con.close();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "error in deletion");
            }
        }
    }//GEN-LAST:event_DeleteBtnActionPerformed
    
    private static boolean isNullOrEmpty(String str) {
        if (str != null && !str.isEmpty()) {
            return false;
        }
        return true;
    }
    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        this.dispose();
        home_page f1 = new home_page();
        f1.setVisible(true);
    }//GEN-LAST:event_HomeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(delete_recipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(delete_recipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(delete_recipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(delete_recipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new delete_recipe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton HomeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
