package recipe_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class my_profile extends javax.swing.JFrame {

    public static final String DATE_FORMAT_NOW = "yyyy-MM-dd";
    
    /**
     * Creates new form my_profile
     */
    public my_profile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        HomeBtn = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        LoadBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(537, 400));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 20)); // NOI18N
        jLabel1.setText("MY PROFILE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(204, 30, 133, 26);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("ENTER EMAIL:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 80, 97, 17);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("DOB:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 180, 35, 22);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("USERNAME:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 130, 83, 17);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("GENDER:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 280, 63, 17);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("ADDRESS:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 230, 70, 17);

        HomeBtn.setBackground(new java.awt.Color(255, 0, 102));
        HomeBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        HomeBtn.setForeground(new java.awt.Color(255, 255, 255));
        HomeBtn.setText("GO BACK TO HOME");
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(HomeBtn);
        HomeBtn.setBounds(70, 320, 167, 30);
        getContentPane().add(t1);
        t1.setBounds(190, 70, 190, 30);

        t2.setEnabled(false);
        getContentPane().add(t2);
        t2.setBounds(190, 170, 190, 30);

        t3.setEnabled(false);
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        getContentPane().add(t3);
        t3.setBounds(190, 220, 190, 30);

        t4.setEnabled(false);
        getContentPane().add(t4);
        t4.setBounds(190, 270, 190, 30);

        t5.setEnabled(false);
        getContentPane().add(t5);
        t5.setBounds(190, 120, 190, 30);

        LoadBtn.setBackground(new java.awt.Color(51, 255, 0));
        LoadBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        LoadBtn.setForeground(new java.awt.Color(255, 255, 255));
        LoadBtn.setText("LOAD");
        LoadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LoadBtn);
        LoadBtn.setBounds(400, 70, 86, 30);

        UpdateBtn.setBackground(new java.awt.Color(0, 0, 255));
        UpdateBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        UpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
        UpdateBtn.setText("UPDATE & SAVE");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateBtn);
        UpdateBtn.setBounds(310, 320, 141, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-70, -40, 665, 443);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        this.dispose();
       home_page f1 = new home_page();
            f1.setVisible(true);
    }//GEN-LAST:event_HomeBtnActionPerformed

    private void LoadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadBtnActionPerformed
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
           String db = "jdbc:mysql://localhost:3306/recipe_system?zeroDateTimeBehavior=convertToNull";
            Connection con = DriverManager.getConnection(db, "root", "P@ssw0rd");
            Statement stmt = con.createStatement();

            String query = "select * from users where email = '" + t1.getText() + "';";
            ResultSet rs = stmt.executeQuery(query);

            String add, username, gen;
            java.sql.Date dob;
            SimpleDateFormat sdf = new SimpleDateFormat(DATE_FORMAT_NOW);
            
            if (rs.next()) {
                dob = rs.getDate("dob");
                add = rs.getString("Address");
                username = rs.getString("username");
                gen = rs.getString("gender");

                t2.setText(sdf.format(dob));
                t3.setText(add);
                t4.setText(gen);
                t5.setText(username);
                
                t2.setEnabled(true);
                t3.setEnabled(true);
                t4.setEnabled(true);
                t5.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "no such record found");
            }
            
            rs.close();
            con.close();
            stmt.close();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "error in connectivity");
            Logger.getLogger(my_profile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LoadBtnActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        int ans = JOptionPane.showConfirmDialog(null, "Are you sure?");
        Connection con = null;
        Statement stmt = null;
        if (ans == JOptionPane.YES_OPTION) {
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String db = "jdbc:mysql://localhost:3306/recipe_system?zeroDateTimeBehavior=convertToNull";
            con = DriverManager.getConnection(db, "root", "P@ssw0rd");
            stmt = con.createStatement();

            String query = "update users set username='" + t5.getText() + "',address='" + t3.getText() +
            "',gender='" + t4.getText() + "',dob='" + t2.getText() + "' where email='" + t1.getText() + "';";
            
                stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(null, "Recipe succesfully updated!");
                
                t1.setText(" ");
                t2.setText(" ");
                t3.setText(" ");
                t4.setText(" ");
                t5.setText(" ");
                
                con.close();
                stmt.close();
                                           
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "error in table updation");
                Logger.getLogger(my_profile.class.getName()).log(Level.SEVERE, null, ex);
            }finally {
                try {
                    if (con != null)
                        con.close();
                    if (stmt != null)
                        stmt.close();
                } catch (SQLException ex) {
                    Logger.getLogger(my_profile.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(my_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(my_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(my_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(my_profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new my_profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HomeBtn;
    private javax.swing.JButton LoadBtn;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    // End of variables declaration//GEN-END:variables
}
